import React, { useMemo } from 'react';
import { SiteDataContext } from './SiteDataContext';
import { validateBeforeRender } from '../utils/dataValidation';

export default function SiteDataProvider({ bootstrap, children }) {
  console.log('📦 SiteDataProvider wrapper mounted');
  
  const value = useMemo(() => {
    if (!bootstrap) {
      // Return default data if no bootstrap provided
      return {
        company_name: 'Your Business Name',
        city: ['Your City'],
        services: 'Your Services',
        colours: ['#ffc000', '#000000'],
        industry: 'Your Industry',
        language: 'English',
        payment_plans: null,
        hero_video: null,
        social: {
          facebook: null,
          instagram: null,
          twitter: null,
          linkedin: null,
          youtube: null,
          tiktok: null,
          pinterest: null,
          snapchat: null,
          whatsapp: null,
          telegram: null,
          reddit: null,
          discord: null,
          github: null,
          behance: null,
          dribbble: null,
          medium: null,
          substack: null,
          patreon: null,
          onlyfans: null,
          twitch: null,
          spotify: null,
          apple_music: null,
          soundcloud: null,
          bandcamp: null,
          etsy: null,
          amazon: null,
          ebay: null,
          depop: null,
          poshmark: null,
          mercari: null,
          vinted: null,
          grailed: null,
          reverb: null,
          discogs: null,
          yelp: null,
          tripadvisor: null,
          foursquare: null,
          zomato: null,
          opentable: null,
          resy: null,
          booksy: null,
          classpass: null,
          mindbody: null,
          eventbrite: null,
          meetup: null,
          facebook_events: null,
          airbnb: null,
          vrbo: null,
          booking: null,
          expedia: null,
          hotels: null,
          kayak: null,
          skyscanner: null,
          uber: null,
          lyft: null,
          doordash: null,
          ubereats: null,
          grubhub: null,
          postmates: null,
          instacart: null,
          shipt: null,
          gopuff: null,
          wolt: null,
          deliveroo: null,
          just_eat: null,
          seamless: null,
          caviar: null,
          eat24: null,
          slice: null,
          menulog: null,
          foodpanda: null,
          swiggy: null,
          zomato_delivery: null,
          grab: null,
          gojek: null,
          ola: null,
          didi: null,
          bolt: null,
          free_now: null,
          kapten: null,
          via: null,
          juno: null,
          curb: null,
          gett: null,
          hailo: null,
          mytaxi: null,
          blacklane: null,
          addison_lee: null,
          kabbee: null,
          minicabit: null,
          uber_for_business: null,
          lyft_business: null,
          enterprise: null,
          hertz: null,
          avis: null,
          budget: null,
          national: null,
          alamo: null,
          thrifty: null,
          dollar: null,
          payless: null,
          advantage: null,
          ace: null,
          fox: null,
          sixt: null,
          europcar: null,
          zipcar: null,
          car2go: null,
          drivenow: null,
          sharenow: null,
          getaround: null,
          turo: null,
          car_next_door: null,
          drivy: null,
          snappcar: null,
          hiyacar: null,
          karshare: null,
          city_car_club: null,
          modo: null,
          evo: null,
          communauto: null,
          autolib: null,
          bluely: null,
          bluetorino: null,
          bluecar: null,
          blueindy: null,
          bluecub: null,
          bluesg: null,
          bluecalifornia: null,
          bluela: null,
          bluesystems: null,
          bluecity: null,
          bluemove: null,
          bluegreen: null,
          bluefleet: null,
          bluelogistics: null,
          bluedelivery: null,
          bluecargo: null,
          bluetruck: null,
          bluevan: null,
          bluebike: null,
          bluescooter: null,
          blueboard: null,
          blueboat: null,
          blueplane: null,
          bluetrain: null,
          bluebus: null,
          bluemetro: null,
          bluetram: null,
          bluesubway: null,
          bluetaxi: null,
          blueride: null,
          bluewalk: null,
          bluerun: null,
          bluejog: null,
          bluehike: null,
          blueclimb: null,
          blueswim: null,
          bluesurf: null,
          bluedive: null,
          bluefish: null,
          bluehunt: null,
          bluecamp: null,
          bluepicnic: null,
          bluebbq: null,
          blueparty: null,
          bluewedding: null,
          blueanniversary: null,
          bluebirthday: null,
          bluegraduation: null,
          bluereunion: null,
          blueholiday: null,
          bluevacation: null,
          bluetrip: null,
          bluejourney: null,
          blueadventure: null,
          blueexploration: null,
          bluediscovery: null,
          blueexperience: null,
          bluememory: null,
          bluestory: null,
          bluedream: null,
          bluehope: null,
          bluelove: null,
          blueheart: null,
          bluesoul: null,
          bluespirit: null,
          bluemind: null,
          bluethought: null,
          blueidea: null,
          blueconcept: null,
          blueplan: null,
          bluegoal: null,
          blueobjective: null,
          bluepurpose: null,
          bluemission: null,
          bluevision: null,
          bluevalue: null,
          blueprinciple: null,
          blueethic: null,
          bluemoral: null,
          blueright: null,
          bluewrong: null,
          bluegood: null,
          bluebad: null,
          bluetrue: null,
          bluefalse: null,
          blueyes: null,
          blueno: null,
          blueup: null,
          bluedown: null,
          blueleft: null,
          blueforward: null,
          bluebackward: null,
          bluein: null,
          blueout: null,
          blueon: null,
          blueoff: null,
          blueopen: null,
          blueclose: null,
          bluestart: null,
          bluestop: null,
          bluebegin: null,
          blueend: null,
          bluefirst: null,
          bluelast: null,
          bluenext: null,
          blueprevious: null,
          bluehere: null,
          bluethere: null,
          bluenow: null,
          bluethen: null,
          bluetoday: null,
          bluetomorrow: null,
          blueyesterday: null,
          bluethis: null,
          bluethat: null,
          bluesome: null,
          blueall: null,
          blueany: null,
          bluenone: null,
          blueone: null,
          bluetwo: null,
          bluethree: null,
          bluefour: null,
          bluefive: null,
          bluesix: null,
          blueseven: null,
          blueeight: null,
          bluenine: null,
          blueten: null
        },
        team: [],
        photos: [],
        reviews: [],
        images: [],
        contact: {
          phone: null,
          email: null,
          address: null,
          website: null
        },
        business_hours: [],
        maps_url: null,
        logo: null,
        favicon: null,
        meta: {
          title: null,
          description: null,
          keywords: null
        }
      };
    }

    // Validate data before rendering
    const validationResult = validateBeforeRender(bootstrap);
    if (!validationResult.passed) {
      console.warn('⚠️ Data validation failed:', validationResult);
      return null;
    }

    return bootstrap;
  }, [bootstrap]);

  return (
    <SiteDataContext.Provider value={value}>
      {children}
    </SiteDataContext.Provider>
  );
}